### PR TITLE
Changes revoke command to remove

### PR DESCRIPTION
**Pull request by frankcash**
`keybase revoke` => `keybase remove`.

fixes dialogues and test that uses it. (#131)

### CODE REVIEW

**Comment by bryangarza** [comment]
look good 👍

**Comment by oconnor663** [comment]
Could you give me some context on this PR? It looks like this just changes a test without touching any of the client code. (Also for what it's worth, we're about to start rolling out the Go reimplementation, so this codebase is slated for retirement.)

**Comment by frankcash** [comment]
Oh, if this codebase is going to be retired this is probably at moot point.  

This PR changes the test `test/lib/user.iced` and the client file `lib/command/revoke.js`.  This change was in reference to issue #131 which I'll admit is an "aged" issue.  The issue stated was that the term "revoke" was a bit misleading and "remove-key" was a more accurate term, thus I changed the arg to be "-remove-key" instead of "-revoke".

**Comment by oconnor663** [comment]
Oh, that's what confused me. `revoke.js` is a generated file, and github suppressed it in the diff. (How they figure that stuff out, I don't know.) What you'd want to do is to edit `src/revoke.iced` and then rerun make. You'll need IcedCoffeeScript installed first. But yes, probably moot at this point.

I always thought the name of that command should be `nuke-my-whole-account`, cause that's pretty much what it does. With the Go client you'll finally be able to add multiple keys to your account and revoke them individually, so the name will make much more sense. Still not the same as a PGP key revocation statement though.

**Pull request closed without merging**
