### PR TITLE
dns.resolveTxt returns Array of Arrays, check for actual string value

### PR DESCRIPTION
**Pull request by ojab**
Right now DNS checks are failing, because dns.resolveTxt returns array of one element arrays (part of `keybase --debug id ojab`):
>debug: ------ Quarantined / oneshot verify -> ok! (fp=9456678949576423A6D59536DA0B5791C1D98E48)
>debug: ----- GpgKey::verify_sig ojab@dns -> null
>debug: |||| remote service desc is {"domain":"ojab.ru","protocol":"dns"}
>debug: +++++ Calling into scraper -> {"domain":"ojab.ru","protocol":"dns"}@dns -> dns://ojab.ru
>debug: ++++++ DNS check for ojab.ru
>debug: |||||| DNS failed; found TXT entries: [["v=spf1 include:_spf.google.com ~all"],["keybase-site->verification=XJLdtaNNaAQiXaVKGS8L4YE2Sx-eC7zqD4Qb6G-Fqf0"]]
>debug: ------ DNS check for ojab.ru -> 201
>debug: ++++++ DNS check for _keybase.ojab.ru
>debug: |||||| DNS failed; found TXT entries: [["keybase-site-verification=XJLdtaNNaAQiXaVKGS8L4YE2Sx-eC7zqD4Qb6G-Fqf0"]]
>debug: ------ DNS check for _keybase.ojab.ru -> 201
>debug: ----- Called scraper -> 201
>✖ admin of the DNS zone for ojab.ru (failed with code 201)
>debug: ---- ojab: checked remote dns proof

This PR fixes the issue here. Unfortunately I haven't found any contributing guide, so dont't know if JS (or other) parts should be changed as well.

### CODE REVIEW

**Comment by ojab** [comment]
And looks like this should go to [keybase/proofs](http://www.github.com/keybase/proofs), right?

**Comment by maxtaco** [comment]
Yes, it should.  Did this recently change in node?  Which version of node are you running?

**Comment by ojab** [comment]
Looks like that was changed in 0.12.0 https://github.com/joyent/node/commit/7b72e156655afb6b998e8fb731cc65f4facb19ee (and node-0.12.0 here), Filled https://github.com/keybase/proofs/pull/17.

**Comment by dns** [comment]
Excuse me, please don't link my username "dns". 
I always keep getting github notification from your github project.

**Pull request closed without merging**
